### ISSUE TITLE
Como executar ou um executável

### ISSUE THREAD

**Issue by alt-art** [ParzivalAD/code-tray-java#1]
Eu queria que explica-se como se executa ou um executável no release

**Comment by AllefDouglasDev** [comment]
Você pode executá-lo rodando o arquivo CodeTray.jar na pasta dist. Ou abrir o projeto em uma IDE (Eclipse ou IntellJIDEA) e rodar a classe main/App.java

**Comment by AllefDouglasDev** [comment]
Adicionei um README explicando como usar. Pode dar uma olhada e ver se consegue usar e as sugestões que tem pra melhorar?

**Comment by alt-art** [comment]
Pode deixar
